title: Tiny Logs
author: loong0
description: >
  Scraps and Drops in this world
# baseurl: "/blog"
url: "https://longlene.github.io"
github_username: longlene

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
