title: Tiny Logs
author: cc
description: >
  Scraps and Drops in this world
# baseurl: "/blog"
url: "https://longlene.github.io"
github_username: longlene

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
