title: Tiny Matrix
author: loong0
description: >
  C/C++, Go, Ruby, Common Lisp
baseurl: ""
url: "http://longlene.me"
twitter_username: longlene
github_username:  longlene

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
